defaults: &defaults
  domain: <%= ENV["DOMAIN"] || "http://lamp.electrolamp.org" %>
  particle_access_token: <%= ENV["PARTICLE_ACCESS_TOKEN"] %>
  invite_hashids_salt: <%= ENV["INVITE_HASHIDS_SALT"] %>
  share_hashids_salt: <%= ENV["SHARE_HASHIDS_SALT"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

development:
  <<: *defaults
  domain: <%= ENV["DOMAIN"] || "http://localhost:3000" %>
  secret_key_base: 96851d25290ed200b1c875d32a8f586b01b7e591336ea6a6a73f4ba09ec391d542350be9007e5014eeccddd8c54cff22fcd929a409b27bdca18ea405b3396293

test:
  <<: *defaults
  secret_key_base: 44c08b4595c72f91737460eedf99b4a929ddff95a4aeb761efe33da0925f9b76d89cfab74cc92f796f9a17c61c91da4013451bcc51e778e95c4212c350939978

production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
